### DISCUSSION TITLE
not able to add background color inside circle text, can you please help me for that ?

### DISCUSSION THREAD

**Discussion by nikul-taurusdevsync** [tomik23/circular-progress-bar#67] [General]
![image](https://user-images.githubusercontent.com/100706127/186432834-792df6f9-1021-4960-8cf6-761e74b2272d.png)

**Comment by tomickigrzegorz** [comment]
Hi,
The usual styles of no magic will do.

```
<div class="pie" data-pie='{ "percent": 75 }'></div>
```

```css
.pie {
  position: relative;
  z-index: 1;
}
.pie::after {
  position: absolute;
  content: "";
  width: 120px;
  height: 120px;
  background-color: #b1b1b1;
  left: calc(50% - 60px);
  border-radius: 50%;
  z-index: 0;
  top: 0;
  bottom: 0;
  margin: auto;
}
svg {
  position: relative;
  z-index: 1;
}
```
